# This test doesn't work for now, there is still more I need to learn here.

class NumberGen:
    """
    This was an attempt at making a generator object.

    It should generate numbers from 0 to 10 when called. Doesn't work as
    intended for now. DO NOT USE.
    """
    def __init__(self, start=0):
        self.value = start

    def __iter__(self):
        return self

    def __next__(self):
        if self.value > 10:
            raise StopIteration
        value = self.value
        self.value += 1
        return value


def number_gen():
    """
    Function to generate a number using a generator class object.

    Doesn't work as intended for now. DO NOT USE.

    :return: 'result', an int generated by the class object 'NumberGen()'.
    """
    result = NumberGen()
    return result
